#!/bin/bash
set -eu
set -o xtrace

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck disable=SC1090
. "$basedir/lib/shared.bash"

path="$1"
action="${2:-get}"

# we only support get and we don't parse the stdin params
if [ "$action" == "get" ] ; then

  # read git-credentials, which is a list of uris
  secret_download "${path}" | while read -r uri ; do
    if ! parse_url "$uri" ; then
      echo "Failed to parse uri $uri" >&2
      exit 1
    fi

    # https://git-scm.com/docs/git-credential#IOFMT
    echo "protocol=${uri_schema}"
    echo "host=${uri_host}"
    echo "username=${uri_user}"
    echo "password=${uri_password}"
  done
fi
