#!/bin/bash

set -eu -o pipefail

_source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

get-ssm () {
  aws ssm get-parameter --name "$1" --query "Parameter.Value" --with-decryption --output text
}

# shellcheck disable=SC1090
[ -f "${_source_dir}/custom-defaults" ] && source "${_source_dir}/custom-defaults"

if [ -n "${AWS_PARAMSTORE_SECRETS_GLOBAL_SSH}" ]
then
  # AWS_PARAMSTORE_SECRETS_GLOBAL_SSH can optionally be a list delimited by `:`
  GLOBAL_SSH_KEYS=(${AWS_PARAMSTORE_SECRETS_GLOBAL_SSH//:/ })
  eval $(/usr/bin/ssh-agent | sed "/^echo/d")
  for KEY in ${GLOBAL_SSH_KEYS[@]}
  do
    echo "Adding ${KEY} deploy key to a default SSH agent"
    # shellcheck disable=SC2046
    get-ssm "${KEY}" | ssh-add - 2>/dev/null
  done
fi

exports=$(bk-ssm-secrets)

set -o allexport
# shellcheck disable=SC1090
source <( echo "$exports" )
set +o allexport

unset -f get-ssm
unset -v exports