#!/bin/bash

#set -o xtrace
set -eu -o pipefail

_source="${BASH_SOURCE[0]}"
_source_dir="$( cd "$( dirname "${_source}" )" && cd .. && pwd )"

# shellcheck disable=SC1090
[ -f "${_source_dir}/custom-defaults" ] && source "${_source_dir}/custom-defaults"

# shellcheck disable=SC2034
env_before="$(env | sort)"  # used by dumpEnvSecrets

envscript="$(PYTHONPATH="${_source_dir}:${PYTHONPATH:-}" BUILDKITE_PLUGIN_AWS_PARAMSTORE_SECRETS_DUMP_ENV=true /usr/local/bin/bk-ssm-secrets)"
set -o allexport
eval "$envscript"
set +o allexport
