#!/bin/bash

if [[ -n "${SSH_AGENT_PID:-}" ]] && ps -p "$SSH_AGENT_PID" &>/dev/null; then
  echo "~~~ Stopping ssh-agent ${SSH_AGENT_PID}"
  ssh-agent -k
fi

if [[ -n "${BK_SSM_SSH_AGENT_REPO_AGENT_PID:-}" ]] && ps -p  "${BK_SSM_SSH_AGENT_REPO_AGENT_PID}" &>/dev/null
then
  echo "~~~ Stopping ssh-agent ${BK_SSM_SSH_AGENT_REPO_AGENT_PID}"
  kill "${BK_SSM_SSH_AGENT_REPO_AGENT_PID}"
fi

unset BK_SSM_SSH_AGENT_REPO_AGENT_PID
unset BK_SSM_SSH_AGENT_REPO_AUTH_SOCK

if [[ -n "${BK_SSM_SSH_AGENT_PROJECT_AGENT_PID:-}" ]] && ps -p  "${BK_SSM_SSH_AGENT_PROJECT_AGENT_PID}" &>/dev/null
then
  echo "~~~ Stopping ssh-agent ${BK_SSM_SSH_AGENT_PROJECT_AGENT_PID}"
  kill "${BK_SSM_SSH_AGENT_PROJECT_AGENT_PID}"
fi

unset BK_SSM_SSH_AGENT_PROJECT_AGENT_PID
unset BK_SSM_SSH_AGENT_PROJECT_AUTH_SOCK