#!/bin/bash

if [[ -n "${SSH_AGENT_PID:-}" ]] && ps -p "$SSH_AGENT_PID" &>/dev/null; then
  echo "~~~ Stopping ssh-agent ${SSH_AGENT_PID}"
  ssh-agent -k
fi

if [[ -n "${AWS_PARAMSTORE_SECRETS_AGENT_PID:-}" ]] && ps -p  "${AWS_PARAMSTORE_SECRETS_AGENT_PID}" &>/dev/null
then
  echo "~~~ Stopping ssh-agent ${AWS_PARAMSTORE_SECRETS_AGENT_PID}"
  kill "${AWS_PARAMSTORE_SECRETS_AGENT_PID}"
fi

unset AWS_PARAMSTORE_SECRETS_REPO_AGENT_PID
unset AWS_PARAMSTORE_SECRETS_REPO_AUTH_SOCK