#!/bin/bash

export ORIG_SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"
export ORIG_SSH_AGENT_PID="${SSH_AGENT_PID}"

try-ssh () {
  success="true"
  SSH_AUTH_SOCK=$1 SSH_AGENT_PID=$2 git ls-remote -q "$BUILDKITE_REPO" 2>/dev/null >/dev/null || success="false"
  echo "$success"
}

repo_works=$(try-ssh "${AWS_PARAMSTORE_SECRETS_REPO_AUTH_SOCK}" "${AWS_PARAMSTORE_SECRETS_REPO_AGENT_PID}")
if [ "$repo_works" = "true" ]
then
  export SSH_AUTH_SOCK="${AWS_PARAMSTORE_SECRETS_REPO_AUTH_SOCK}"
  export SSH_AGENT_PID="${AWS_PARAMSTORE_SECRETS_REPO_AGENT_PID}"
else
  project_works=$(try-ssh "${AWS_PARAMSTORE_SECRETS_PROJECT_AUTH_SOCK}" "${AWS_PARAMSTORE_SECRETS_PROJECT_AGENT_PID}")
  if [ "$project_works" = "true" ]
  then
    export SSH_AUTH_SOCK="${AWS_PARAMSTORE_SECRETS_PROJECT_AUTH_SOCK}"
    export SSH_AGENT_PID="${AWS_PARAMSTORE_SECRETS_PROJECT_AGENT_PID}"
  else
    >&2 echo "No ssh agent works. Using the default one"
  fi
fi
